-- MySQL Script generated by MySQL Workbench
-- Fri May 19 18:27:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema celulares
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema celulares
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `celulares` DEFAULT CHARACTER SET utf8 ;
USE `celulares` ;

-- -----------------------------------------------------
-- Table `celulares`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celulares`.`personas` (
  `idpersonas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpersonas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `celulares`.`precios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celulares`.`precios` (
  `idprecios` INT NOT NULL AUTO_INCREMENT,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprecios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `celulares`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celulares`.`modelos` (
  `idmodelos` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmodelos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `celulares`.`celulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celulares`.`celulares` (
  `idcelulares` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(20) NOT NULL,
  `fk_precios` INT NOT NULL,
  `fk_modelos` INT NOT NULL,
  PRIMARY KEY (`idcelulares`),
  INDEX `fk_celulares_precios1_idx` (`fk_precios` ASC) VISIBLE,
  INDEX `fk_celulares_modelos1_idx` (`fk_modelos` ASC) VISIBLE,
  CONSTRAINT `fk_celulares_precios1`
    FOREIGN KEY (`fk_precios`)
    REFERENCES `celulares`.`precios` (`idprecios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_celulares_modelos1`
    FOREIGN KEY (`fk_modelos`)
    REFERENCES `celulares`.`modelos` (`idmodelos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `celulares`.`celularespersonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `celulares`.`celularespersonas` (
  `idcelularpersona` INT NOT NULL,
  `fk_personas` INT NOT NULL,
  `fk_celulares` INT NOT NULL,
  INDEX `fk_personas_has_celulares_celulares1_idx` (`fk_celulares` ASC) VISIBLE,
  INDEX `fk_personas_has_celulares_personas1_idx` (`fk_personas` ASC) VISIBLE,
  PRIMARY KEY (`idcelularpersona`),
  CONSTRAINT `fk_personas_has_celulares_personas1`
    FOREIGN KEY (`fk_personas`)
    REFERENCES `celulares`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_has_celulares_celulares1`
    FOREIGN KEY (`fk_celulares`)
    REFERENCES `celulares`.`celulares` (`idcelulares`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
